### ISSUE TITLE
login

### ISSUE THREAD

**Issue by maxmonz69** [ndg63276/smartlife#15]
Hi,
I downloaded and tried your application from my pc.
I entered credential I use to log on tuya web and login failed.
Maybe I didn't understand. Which credentials do I need? For which site?

**Comment by ndg63276** [comment]
Use the credentials that you would usually use on the SmartLife or Tuya apps. Use them to login to smartathome.co.uk.

**Comment by tvogel** [comment]
I cannot login eithar and it seems to be caused by rate-limits:

```json
{"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}
```

It seems, you are using the homeassistant end-point. Is there a way to register another end-point?

**Comment by qpzmp** [comment]
You get the 180 seconds error if you retry too quickly with the same credentials.  The initial failure message is "accesstoken failed. Username or password error!".  I get this error when I use the same email and password that I use successfully on the iPhone app.

Is there any way to understand what the issue is?

**Comment by ndg63276** [comment]
Unfortunately you all get the same info as I do. If you get an error, wait at least 3 minutes, try again. Make sure to type your password in correctly. Make sure you have chosen the right region. Make sure you have chosen the right platform.

If you want to register another endpoint, you are free to fork the code.

**Comment by qpzmp** [comment]
Thanks for that.  

I get the same error, whether I go via your web site or the copy I downloaded to my own PC.  Would this mean that the endpoint you mention, is not a factor?

With regards to the endpoint, I can't see any reference to an endpoint in your code, have you registered your server with Tuya?

I have also tried experimenting with removing "biztype" and "from" from the data json and get the repsonse "Get accesstoken failed. Invalid parms.", which would suggest that the error messages are specific to what the detected issue is and so is it reasonable to expect it to also indicate if it was not specifically the username and/or password that it had an issue with?

**Comment by qpzmp** [comment]
I seem to have solved it.
The copy of the code I downloaded from Github did not have the platform option and I missed it when using you own website.
Changing the hard coded "bizType": "smart_life" to "bizType": "tuya", seems to have worked.
Thanks once again for your help
