### ISSUE TITLE
Region issue

### ISSUE THREAD

**Issue by ChoonKwang** [ndg63276/smartlife#3]
Hi, may i know if i have an account in singapore. How do i change the region and the endpoints url? Or the API is only for EU now?

**Comment by ndg63276** [comment]
If you have logged in to the wrong region, you should delete your cookies, then you get the dropdown again. There is no Singapore region though AFAIK, only US, EU or CN.

**Comment by ChoonKwang** [comment]
Thank you. I found out that even when i registered Singapore in the smartlife app, the region is still under EU. Just a good knowledge for whoever trying to integrate with this.
