### ISSUE TITLE
Message Center API

### ISSUE THREAD

**Issue by ChoonKwang** [ndg63276/smartlife#4]
Hi, just wondering is there a way to pull the message center/alerts from tuya using a similar ajax functions? Really appreciate if you can guide me to the payload message header or to include in the future updates. I would love to make a donation to support this awesome project!

**Comment by ndg63276** [comment]
Hello. I based my code on the tuyapy (https://pypi.org/project/tuyapy/) project, and the tuyaha (https://github.com/PaulAnnekov/tuyaha) project that continued using it. I haven't seen any documentation, so I don't know any way to see the message center, but do let me know if you see anything.

Sponsorship always welcome via https://github.com/sponsors/ndg63276/dashboard :-)
