### ISSUE TITLE
Cant login with this API

### ISSUE THREAD

**Issue by zulguamusang** [ndg63276/smartlife#6]
Hi, why i cant login to access smart life devices with this API?

Already changed country code to 60

var data = {
		"userName": username,
		"password": password,
		"countryCode": 60,
		"bizType": "smart_life",
		"from": "tuya",
	}

get login failed error, I'm sure username and pass is right because i can login with the smartlife apps..

Am i wrong something here?

Btw, I'm from Malaysia

**Comment by ndg63276** [comment]
I think the only valid country codes are 44 (for Europe), 1 (for US) and 86 (for China). Can you try with one of those?
