### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by toburger** [ndg63276/smartlife#9]
Hi, I've tried the three regions including 39 for Italy (I'm from Italy) but I get 

```json
{"responseStatus":"error","errorMsg":"Get accesstoken failed. Username or password error!"}
```

for all regions.

I am sure I am using the correct login and password: _logged out, closed the app and logged back into the Smart Life app with the same credentials on my iPhone_.

**Comment by ndg63276** [comment]
How odd, it's still working fine for me. Are you using a username or an email address? Does your password contain any weird characters? Could you try changing it to something simple temporarily?

**Comment by toburger** [comment]
I am using indeed an email address as username. I've tried to URL escape the address and I use now a very simple password but I still get the same error.

**Comment by ndg63276** [comment]
Are you using https://smartathome.co.uk/smartlife/index.html or deploying the repo yourself?

**Comment by ndg63276** [comment]
It should be the same credentials used in the Smart Life app, ie https://play.google.com/store/apps/details?id=com.tuya.smartlife

Obviously that lets you choose country and my site has region, but the email and password should be the same. I don't really know what else to say, I don't have any access to the smart life servers so I cant see what's going wrong.

**Comment by toburger** [comment]
No worries! Looks like I have something strange going on if I am the only one with that kind of problems. Thanks for your help!

As a workaround I was able to use Alexa to control my devices.
